### ISSUE TITLE
Seeing this java.lang.NoSuchMethodError with 1.0 when trying to run make task

### ISSUE THREAD

**Issue by ysb33r** [ysb33r/gnumake-gradle-plugin#3]
```
java.lang.NoSuchMethodError: org.gradle.util.CollectionUtils.stringize(Ljava/util/List;)Ljava/util/List;
        at org.ysb33r.gradle.gnumake.GnuMakeBuild.getTargets(GnuMakeBuild.groovy:101)
        at org.ysb33r.gradle.gnumake.GnuMakeBuild_Decorated.getTargets(Unknown Source)
```

Was running with JDK 1.8 and Gradle 2.3.

**Comment by ysb33r** [comment]
It can be confirmed that this is a problem with Gradle 2.2+.

**Comment by ysb33r** [comment]
FIxed in RELEASE_1_0_1
